models:
  path: "/this/is/the/path/to/model"

mongoDb:
  host: !!str "localhost"
  port: !!int 27017

  credentials:
    user: !!str "user"
    pwd: !!str "password"

  collections:
    - users
    - transactions



